[package]
name = "ray_tracing_in_one_weekend"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
rand = "0.8.5"
rayon = "1.9.0"
clap = "4.5.4"

[profile.release]
opt-level = 3
lto = true
strip = true
